Added Python 3.11 image

diff --git a/src/python/_common/prepare b/src/python/_common/prepare
--- a/src/python/_common/prepare
+++ b/src/python/_common/prepare
@@ -4,6 +4,16 @@
 python -m pip install enum34 unittest-xml-reporting
 
 # Ruby is necessary for CI infrastructure
-apk add --no-cache \
+apk update
+apk add \
 	ruby \
 	ruby-json
+
+# Modern Ruby doesn't ship by default with rexml-doc, so we check if this needs extra install
+if ! echo 'require "rexml/document"' | ruby; then
+	echo "no rexml/document detected, installing"
+	apk add ruby-rexml
+fi
+
+# Cleanup apk cache
+rm -rf /var/cache/apk/*
